### ISSUE TITLE
Brainstorm ideas

### ISSUE THREAD

**Issue by SasanTazayoni** [SasanTazayoni/PhantomForge#1]
This is an open-ended project so we have to collectively decide exactly what we are going to make. Have a look at ideas online and try to come up with something for Thursday 7PM (UK time). Try to avoid ideas that are complicated because we do not have a lot of time.

**Comment by richard9106** [comment]
I like some of ideas of Szymon Halloween Trivial, or something like Netfilx of terror

**Comment by Goncalves95** [comment]
Ghost Hide-and-Seek
is a thematic and fun version of the classic "Hide and Seek" game. In this game, there are a certain number of ghosts hidden in a haunted scene. The player's objective is to find all the ghosts by clicking on them. Each time a ghost is discovered, a message informs that the corresponding ghost has been found. The game continues until all the ghosts have been found. The player is congratulated upon finding all the ghosts, and a completion message is displayed.

The player must use their powers of observation and concentration to locate and click on the hidden ghosts as quickly as possible. The game is designed to be a fun and exciting activity, with the thrill of uncovering each ghost and the satisfaction of finding them all in the end.
