### ISSUE TITLE
Colour scheme

### ISSUE THREAD

**Issue by SasanTazayoni** [SasanTazayoni/PhantomForge#2]
A nice colour scheme would be great since this is primarily a UI/UX project (black and orange are pretty effective).

**Comment by Goncalves95** [comment]
Black: #000000 (solid and background colour to create a gloomy atmosphere)

Dark Orange: #FF8C00 (to add contrast and draw attention to important elements)

Dark Grey: #333333 (for additional details and contrast balance)

White: #FFFFFF (for text and elements that need to stand out against the dark background)
