### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by SasanTazayoni** [SasanTazayoni/PhantomForge#3]
Pick a spooky font pair!

**Comment by richard9106** [comment]
1 - Creepster/ googlefonts 
2 - Alumni Sans Collegiate One/ googlefonts
3-Nosifer / googlefonts

or in this page have a lot of font like halloween

**Comment by richard9106** [comment]
https://www.dafont.com/es/theme.php?cat=110

**Comment by SasanTazayoni** [comment]
Good job on looking those up Richard, we will discuss further in the meeting, I have assigned you this task.

**Comment by Goncalves95** [comment]
https://fonts.google.com/specimen/Cinzel

**Comment by richard9106** [comment]
Delicious Handrawn/google fonts

**Comment by SasanTazayoni** [comment]
We decided on Creepster for headings and signika for body text
