### ISSUE TITLE
Gallery grid

### ISSUE THREAD

**Issue by SasanTazayoni** [SasanTazayoni/PhantomForge#30]
The current style of the gallery is already very nice, but we could add:

* A small grid gap between the pictures
* A glow hover effect on the pictures
* Pictures to be clickable to open a modal showing the selected picture enlarged
* A border-radius on each picture giving them a "card-like" appearance

**Comment by ObiOne84** [comment]
The most of it is resolved. Some minor tweak and I will add some animation to the gallery.
